#!/usr/bin/env bash
#Transer file from a client to a server
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/  # Add space before the comment
    if [ $? -eq 0 ]; then
        echo "File transferred successfully!"
    else
        echo "Error transferring file. Check your parameters and try again."
    fi
fi
