#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Add the redirect configuration
sudo bash -c 'cat <<EOL > /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        rewrite ^/redirect_me https://twitter.com/jossvega103 permanent;
    }
}
EOL'

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
