#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page

# Update package information
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Create the index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add redirection rule
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/jossvega103 permanent;" /etc/nginx/sites-enabled/default

# Create the custom 404 page file
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_error_404.html

# Add configuration for the custom 404 page
sudo sed -i '37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n' /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart
