#!/usr/bin/env bash
#impliment a clock
# Initialize hours and minutes
hours=0
minutes=1

# Using a while loop to display time for 12 hours and 59 minutes
while [ $hours -le 12 ]
do
    echo "$hours:$minutes"
    
    # Increment minutes
    ((minutes++))
    
    # Check if minutes reached 60, reset minutes and increment hours
    if [ $minutes -eq 60 ]; then
        minutes=1
        ((hours++))
    fi
done
