#!/usr/bin/env bash
#display files in the directory
# Iterate through files in the current directory
for file in *
do
    # Check if the file is not hidden and contains a dash
    if [ ! -d "$file" ] && [[ "$file" == *-* ]]
    then
        # Extract part of the name after the first dash
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done
