#!/usr/bn/env bash
#configure ufw firewall to block incoming trafic
#except for tcp ports 22 80 443

sudo apt install ufw
sudo ufw default deny incoming
sudo default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
